# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "naruse-tf-backend"
    dynamodb_table = "naruse-tf-backend"
    encrypt        = true
    key            = "aws-labo/env/s3_cloudfront_static_website.tfstate"
    region         = "ap-northeast-1"
  }
}
