# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "naruse-tf-backend"
    dynamodb_table = "naruse-tf-backend"
    encrypt        = true
    key            = "aws-labo/env/ecs_on_fargate.tfstate"
    region         = "ap-northeast-1"
  }
}
